nickkro25/cse112_team15

css/style.css, tests/statistics.test.js
- Closes #24 
- Changed the width of the timer display container to relative
- Fixed the top-left and bottom-right border positions
- The timer display now centers on screen
- Nope
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and performance of the website. Check for consistency of code style.
=> timer centered in css

index.html
- Closes #37 
- Added startTimer button to waves-effect class
- Nope
=> top of button now clickable

README.md
- N/A
Changed name of repo in readme
- TODO 
=> change readme with current repo info

css/style.css
N/A
- Fixed timer width so that the width will not be larger than the mobile screen width
N/A
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and performance of the website. Check for consistency of code style.
=> Bug: timer width

css/faq-box.css, css/stats.css, css/style.css
N/A
- Modify timer corner
- Modify the width of stats window in mobile screen
- Modify the faq box so that it is above the settings
- Modify the faq box in mobile screen
- TODO 
=> Bug: Timer Corner, Stats window, Faq box

css/settings.css
- Closes #58
- settings.css: Set the color of all three time inputs to a constant black
- TODO 
=> fixes custom timer length setting in dark mode

css/table.css, index.html, js/Misc/Settings.js
- Closes <#15>
Changed Settings.js to add color change to broken buttons and other elements. Added couple of id attributes to certain elements.
Dark Mode Off: 
Dark Mode On: 
- TODO 
- TODO 
=> Fixed nightmode inconsistency

css/settings.css
- Closes #58
- Same changes as before, was nuked on a recent commit
- TODO 
=> Custom time length in dark mode bug re-fixed

index.html, js/Misc/Settings.js
- Closes #83 
Added id attribute for the settings button icon and fixed the JS bug where it makes the icon not clickable.
- TODO 
- TODO 
=> Added id for settings button Icon and fixed JS bug

js/Timer/Timer.js, js/Timer/TimerWorker.js
- Closes #104 
- Removed import statement in TimerWorker
- Added timerToString function directly in TimerWorker
- TODO 
=> Fixed Timer in Firefox

js/Timer/TimerWorker.js
- Closes #108 
- Removed this.end in TimerWorker
- Added timeoutID to keep track of timeouts
- End the timer by interrupting the timeouts instead of using this.end
- TODO 
=> fixed spam start bug

css/table.css, js/App.js, js/Timer/Timer.js, js/Timer/TimerVariables.js
- Closes #94 
- Added new method in Timer.js for resetting the current session
- Trigger the method when distraction is noted
- Close opened distraction page when distraction button is disabled
- TODO 
=> Reset session when distracted

.gitignore, css/ThirdParty/reduced-materialize.css, css/distraction-box.css, css/settings.css, css/style.css, index.html
- Closes #25 
- Fixed validator errors
- TODO 
=> fixed some html validator errors

index.html, js/Timer/Timer.js, tests/timer.test.js
- Closes <#69>
- Added script to ask and save user permission in index.html
- Added corresponding notification when work, short break, or long break along with the web icon.
- TODO 
- Might need to discuss how to explain the user why we need to allow permission (in the intro, small popup, etc.)
- TODO 
Please checkout the branch and try to find bugs that may have slipped through. Check for confusing code, excessive anonymous functions ( should be short 2-3 line functions if anonymous ), and peformance of the website. Check for …
=> Added ask user permission and notifications.

css/style.css
- #117 
- Before & After:
- TODO 
=> bugfix/Weird layout for low-height screen

package.json
renamed the name of repo in package.json file
- copied from PR #93.
- TODO 
=> updated name of package.json to current repo name

css/style.css
- Closes <#99>
- As we added the finish task button, the timer has more space in mobile screen, which looks cramped.
- Modify the position of the timer and the current task in the mobile screen
- Based on #115.
- Before and after:
- TODO 
=> Feature/Hide task list during session (New version)

css/table.css
- Closes <#122>
- Before and after:
- TODO 
=> Fix heading

css/animations.css, css/style.css, css/table.css, index.html, js/App.js, js/Distraction/DistractedByDevice.js, js/Timer/Timer.js, js/Timer/TimerVariables.js, tests/timer.test.js
- Closes #26 #84 
- Fixed CSS validation errors
- Users don't have to scroll anymore, everything fits on screen
- Added fade transition to buttons
- Made start button width consistent (the width of the start button would change before)
- TODO 
=> did some small polishing

css/ThirdParty/reduced-materialize.css
- Closes <#133>
https://user-images.githubusercontent.com/81718264/171069683-fdc047d2-ab70-48d2-b62c-79fca6c134d4.mp4
- TODO 
=> No more transition for faq & statistics buttons

css/style.css
- Closes #148 
- Removed pointer event for the logo so that cursors don't turn into a pointer when hovered over.
- TODO 
=> logo no longer clickable

css/style.css, js/Misc/Settings.js
- #10
- **[NEW] Ensure that the font color of the distraction button is always white**
- Modify the threshold for font color change so that we can still have white font color for some background colors which are not very light
- TODO 
=> getFontColor() Modification

css/style.css, css/table.css, index.html, js/App.js, js/ToDoList/TodoListDom.js
- Closes <#98>
- Added transition effect fade in when focus and fade out when un-focus
- Make current task and mode text larger
- TODO 
- TODO 
=> Added transition effects and emphasize curr task

css/table.css
- Closes #145 
- Modified task list input bar appearance 
N/A
=> Changed input bar appearance

css/animations.css, css/style.css, css/table.css
- Closes #161
- Changed gradient highlight to standard highlight when hovering over tasks in short break mode
- Added highlights when hovering over tasks in long break mode
N/A
=> fixed task highlighting issues in short break and long break

css/settings.css, css/style.css, index.html
=> Updated settings appearance

css/distraction-box.css, css/style.css, index.html
- Closes #154 
- Updated FAQ
- Removed li style from css so that lists work properly in the FAQ, doesn't seem like this breaks anything else on the site
Copied from #164.
=> updated FAQ and removed an unused CSS setting for li

css/settings.css, css/style.css, js/App.js
- Closes #169
- Fixed transition bugs listed in the issue above
N/A
=> Fixed nav, settings text, and current task transitions

css/distraction-box.css, css/style.css, index.html, js/App.js, js/Timer/Timer.js
- Closes #23 
- Added session indicators that fill up as you complete sessions
- Changed distraction modal to fit other modals, removed verbose label
- Fixed mobile transform distance when entering focus mode
N/A
=> Added session indicators

css/style.css, js/App.js
=> Added transition effect for hiding session indicators

css/style.css, js/Timer/Timer.js
- Closes #180
- Added Notification API check so timer doesn't break completely on iOS
N/A
=> Fixed iOS timer bug

index.html
- Closes #173 
Edited index.html to update the FAQ
=> Updated FAQ

css/animations.css, css/table.css, index.html, js/Misc/Settings.js
- Closes #163
- "Delete all" and "add" buttons highlight when hovered
- TODO 
=> Bugfix: "Delete all" and "add" buttons highlight when hovered

js/App.js
- Closes #184 
- Change navBar.style.transitionDuration from 2s to 0.2s
- TODO 
=> Fix Header transition

index.html, js/Timer/Timer.js, tests/timer.test.js
- Closes #172
- Fix Timer change visibility
- TODO 
=> Fix Timer change visibility
